/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { TipPost } from "./TipPost";
export * as factories from "./factories";
export { TipPost__factory } from "./factories/TipPost__factory";
