/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace TipPost {
  export type PostStruct = {
    id: BigNumberish;
    creator: AddressLike;
    imageUrl: string;
    caption: string;
    likes: BigNumberish;
    totalEarned: BigNumberish;
    timestamp: BigNumberish;
  };

  export type PostStructOutput = [
    id: bigint,
    creator: string,
    imageUrl: string,
    caption: string,
    likes: bigint,
    totalEarned: bigint,
    timestamp: bigint
  ] & {
    id: bigint;
    creator: string;
    imageUrl: string;
    caption: string;
    likes: bigint;
    totalEarned: bigint;
    timestamp: bigint;
  };
}

export interface TipPostInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "checkLiked"
      | "createPost"
      | "getAllPosts"
      | "hasLiked"
      | "likeCost"
      | "likePost"
      | "postCount"
      | "posts"
      | "totalEarnedByUser"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "PostCreated" | "PostLiked"): EventFragment;

  encodeFunctionData(
    functionFragment: "checkLiked",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "createPost",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getAllPosts",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "hasLiked",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "likeCost", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "likePost",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "postCount", values?: undefined): string;
  encodeFunctionData(functionFragment: "posts", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "totalEarnedByUser",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "checkLiked", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "createPost", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAllPosts",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "hasLiked", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "likeCost", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "likePost", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "postCount", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "posts", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalEarnedByUser",
    data: BytesLike
  ): Result;
}

export namespace PostCreatedEvent {
  export type InputTuple = [
    id: BigNumberish,
    creator: AddressLike,
    imageUrl: string,
    caption: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    id: bigint,
    creator: string,
    imageUrl: string,
    caption: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    id: bigint;
    creator: string;
    imageUrl: string;
    caption: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PostLikedEvent {
  export type InputTuple = [
    postId: BigNumberish,
    liker: AddressLike,
    creator: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    postId: bigint,
    liker: string,
    creator: string,
    amount: bigint
  ];
  export interface OutputObject {
    postId: bigint;
    liker: string;
    creator: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface TipPost extends BaseContract {
  connect(runner?: ContractRunner | null): TipPost;
  waitForDeployment(): Promise<this>;

  interface: TipPostInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  checkLiked: TypedContractMethod<
    [postId: BigNumberish, user: AddressLike],
    [boolean],
    "view"
  >;

  createPost: TypedContractMethod<
    [imageUrl: string, caption: string],
    [void],
    "nonpayable"
  >;

  getAllPosts: TypedContractMethod<[], [TipPost.PostStructOutput[]], "view">;

  hasLiked: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;

  likeCost: TypedContractMethod<[], [bigint], "view">;

  likePost: TypedContractMethod<[postId: BigNumberish], [void], "payable">;

  postCount: TypedContractMethod<[], [bigint], "view">;

  posts: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, string, bigint, bigint, bigint] & {
        id: bigint;
        creator: string;
        imageUrl: string;
        caption: string;
        likes: bigint;
        totalEarned: bigint;
        timestamp: bigint;
      }
    ],
    "view"
  >;

  totalEarnedByUser: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "checkLiked"
  ): TypedContractMethod<
    [postId: BigNumberish, user: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "createPost"
  ): TypedContractMethod<
    [imageUrl: string, caption: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getAllPosts"
  ): TypedContractMethod<[], [TipPost.PostStructOutput[]], "view">;
  getFunction(
    nameOrSignature: "hasLiked"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "likeCost"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "likePost"
  ): TypedContractMethod<[postId: BigNumberish], [void], "payable">;
  getFunction(
    nameOrSignature: "postCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "posts"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, string, string, bigint, bigint, bigint] & {
        id: bigint;
        creator: string;
        imageUrl: string;
        caption: string;
        likes: bigint;
        totalEarned: bigint;
        timestamp: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "totalEarnedByUser"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  getEvent(
    key: "PostCreated"
  ): TypedContractEvent<
    PostCreatedEvent.InputTuple,
    PostCreatedEvent.OutputTuple,
    PostCreatedEvent.OutputObject
  >;
  getEvent(
    key: "PostLiked"
  ): TypedContractEvent<
    PostLikedEvent.InputTuple,
    PostLikedEvent.OutputTuple,
    PostLikedEvent.OutputObject
  >;

  filters: {
    "PostCreated(uint256,address,string,string,uint256)": TypedContractEvent<
      PostCreatedEvent.InputTuple,
      PostCreatedEvent.OutputTuple,
      PostCreatedEvent.OutputObject
    >;
    PostCreated: TypedContractEvent<
      PostCreatedEvent.InputTuple,
      PostCreatedEvent.OutputTuple,
      PostCreatedEvent.OutputObject
    >;

    "PostLiked(uint256,address,address,uint256)": TypedContractEvent<
      PostLikedEvent.InputTuple,
      PostLikedEvent.OutputTuple,
      PostLikedEvent.OutputObject
    >;
    PostLiked: TypedContractEvent<
      PostLikedEvent.InputTuple,
      PostLikedEvent.OutputTuple,
      PostLikedEvent.OutputObject
    >;
  };
}
